#!/usr/bin/env python3
"""
student_pages.py — map heading identifiers to their page in the student edition.

The teacher's edition carries a cross-reference under each heading saying where
the same material sits in the student's book. The page numbers are not known
until the student edition has been typeset, so they are harvested afterwards
from its .aux file, where XeLaTeX records one \\newlabel per \\label that
pandoc emitted for a heading.

Reads  build/tex/greek-classroom.aux
Writes build/student-pages.lua   (a Lua table, loaded by the pandoc filter)

An .aux entry looks like

    \\newlabel{the-unwelcome-tablet}{{}{12}{The Unwelcome Tablet}{chapter.3}{}}
                 \\___ identifier _/   ^^ page

Braces are matched rather than pattern-matched, because heading titles contain
braces of their own.
"""
import re
import sys
from pathlib import Path

NEWLABEL = re.compile(r"\\newlabel\{")


def read_group(text, i):
    """Read a balanced {...} starting at text[i] == '{'. Returns (body, next_i)."""
    if i >= len(text) or text[i] != "{":
        return None, i
    depth, start = 0, i
    while i < len(text):
        c = text[i]
        if c == "\\":          # skip an escaped character
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i + 1
        i += 1
    return None, i            # unbalanced; caller skips the entry


def parse_aux(text):
    pages = {}
    for m in NEWLABEL.finditer(text):
        ident, i = read_group(text, m.end() - 1)
        if ident is None:
            continue
        # hyperref and cleveref add bookkeeping labels; they are not headings
        if ident.endswith("@cref") or ident.startswith("sub@"):
            continue
        body, _ = read_group(text, i)
        if body is None:
            continue
        _, j = read_group(body, 0)          # {section number}
        page, _ = read_group(body, j)       # {page}
        if page is None:
            continue
        page = page.strip()
        if page.isdigit():                  # roman-numbered front matter is skipped
            pages[ident] = int(page)
    return pages


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: student_pages.py <student.aux> <out.lua>")
    aux, out = Path(sys.argv[1]), Path(sys.argv[2])
    if not aux.exists():
        sys.exit(f"student_pages.py: {aux} not found — build the student edition first")

    pages = parse_aux(aux.read_text(encoding="utf-8", errors="replace"))
    if not pages:
        sys.exit(f"student_pages.py: no headings found in {aux}")

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        fh.write("-- generated by scripts/student_pages.py; do not edit\n")
        fh.write("return {\n")
        for ident in sorted(pages):
            fh.write(f'  ["{ident}"] = {pages[ident]},\n')
        fh.write("}\n")
    print(f"  -> {out} ({len(pages)} headings)")


if __name__ == "__main__":
    main()
